version: 2.1

executors:
  clang-executor:
    docker:
      - image: ubuntu:latest
    resource_class: small
    environment:
      CC: clang
      CXX: clang++

jobs:
  clang-format-check:
    executor: clang-executor
    steps:
      - checkout
      - run:
          name: Install clang-format
          command: |
            export DEBIAN_FRONTEND=noninteractive
            apt update && apt install -y clang-format
      - run:
          name: Run clang-format
          command: |
            find . -name "*.c" -o -name "*.cpp" -o -name "*.h" | xargs clang-format --dry-run --Werror

  clang-tidy-check:
    executor: clang-executor
    steps:
      - checkout
      - run:
          name: Install clang-tidy
          command: |
            export DEBIAN_FRONTEND=noninteractive
            apt update && apt install -y clang-tidy
      - run:
          name: Run clang-tidy
          command: |
            for file in $(find . -name "*.c" -o -name "*.cpp" -o -name "*.h"); do
              clang-tidy $file -- -std=c++17 || exit 1
            done

  build-and-test:
    executor: clang-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            export DEBIAN_FRONTEND=noninteractive
            apt update && apt install -y build-essential cmake
      - run:
          name: Configure and Build with Coverage
          command: |
            mkdir -p build && cd build
            cmake .. -DCMAKE_CXX_FLAGS="--coverage -O0 -g -fprofile-arcs -ftest-coverage"
            make
      - run:
          name: Run Tests
          command: |
            cd build
            make runTests
      - run:
          name: Generate Test Coverage Report
          command: |
            cd build
            lcov --capture --directory . --output-file coverage.info
            lcov --remove coverage.info '/usr/*' '*/test/*' --output-file coverage_filtered.info
            genhtml coverage_filtered.info --output-directory coverage_report
      - store_artifacts:
          path: build/coverage_report
          destination: coverage

workflows:
  version: 2
  clang-checks:
    jobs:
      - clang-format-check
      - clang-tidy-check
      - build-and-test

